openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Swagger RESTful PHP API"
  description: "PHP RESTful API with Swagger"
  license:
    name: MIT
    url: https://opensource.org/license/mit/
servers:
  - url: "http://localhost/PHP-API-Template/"
    description: Chat API local
  - url: "https://api.toolchain.tech/api/chat/v1/"
    description: "Chat API remote"
components:
  securitySchemes:
    identity_server_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "https://demo.identityserver.io/connect/authorize"
          scopes:
            api: "api"
security:
  - identity_server_auth:
    - api
paths:
  /user/get_all:
    get:
      summary: "Returns all users"
      tags:
        - USERS
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"