openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Swagger RESTful PHP API"
  description: "PHP RESTful API with Swagger"
  license:
    name: MIT
    url: https://opensource.org/license/mit/
servers:
  - url: "http://localhost/PHP-API-Template/"
    description: "Chat API local"
  - url: "https://api.toolchain.tech/api/chat/v1/"
    description: "Chat API remote"
paths:
  /user/get_all:
    get:
      tags:
        - USER
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /user/get_by_id:
    get:
      tags:
        - USER
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /user/save_user:
    post:
      tags:
        - USER
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /user/update_user:
    put:
      tags:
        - USER
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /user/delete_user:
    delete:
      tags:
        - USER
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /security/authenticate:
    post:
      tags:
        - SECURITY
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
